# Permission.create(module: "Basic And Personal Details", action: "view", module_id: "profile.index")
# Permission.create(module: "Basic And Personal Details", action: "create", module_id: "profile.create")
# Permission.create(module: "Basic And Personal Details", action: "edit", module_id: "profile.edit")
Permission.create(category: "Employee", module: "Basic And Personal Details", action: "view own", module_id: "profile.view_own")
Permission.create(category: "Employee", module: "Basic And Personal Details", action: "view all", module_id: "profile.view_all")
Permission.create(category: "Employee", module: "Basic And Personal Details", action: "create", module_id: "profile.create")
Permission.create(category: "Employee", module: "Basic And Personal Details", action: "edit own", module_id: "profile.edit_own")
Permission.create(category: "Employee", module: "Basic And Personal Details", action: "edit all", module_id: "profile.edit_all")

Permission.create(category: "Employee", module: "Salary Details", action: "view own", module_id: "salary.view_own")
Permission.create(category: "Employee", module: "Salary Details", action: "view all", module_id: "salary.view_all")
Permission.create(category: "Employee", module: "Salary Details", action: "create", module_id: "salary.create")
Permission.create(category: "Employee", module: "Salary Details", action: "edit own", module_id: "salary.edit_own")
Permission.create(category: "Employee", module: "Salary Details", action: "edit all", module_id: "salary.edit_all")

Permission.create(category: "Employee", module: "Employee Payment Information", action: "view own", module_id: "payment.view_own")
Permission.create(category: "Employee", module: "Employee Payment Information", action: "view all", module_id: "payment.view_all")
Permission.create(category: "Employee", module: "Employee Payment Information", action: "create", module_id: "payment.create")
Permission.create(category: "Employee", module: "Employee Payment Information", action: "edit own", module_id: "payment.edit_own")
Permission.create(category: "Employee", module: "Employee Payment Information", action: "edit all", module_id: "payment.edit_all")

# Permission.create(action: action, subject_class: 'User', role: admin_role, scope: 'others')
